events {}
http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://server:4000/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
      proxy_pass http://admin:3000/;
    }

    location / {
      proxy_pass http://customer:3000/;
    }
  }
}
